# swees <sweespay.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
]

[DOCUMENTATION]
ORG_NAME="trumpstellar"
ORG_URL="https://trumpstellar.github.io/"
ORG_LOGO ="https://trumpstellar.github.io/img/crown.png"
ORG_OFFICIAL_EMAIL="trumpstellar@FINANCE"
ORG_SUPPORT_EMAIL="trumpstellar@FINANCE"
ORG_DESCRIPTION="trumpstellar FINANCE"

[[PRINCIPALS]]
email="trumpstellar@FINANCE"

[[CURRENCIES]]
code ="TRUMP"
name ="TRUMP"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="Thes is make all type of payment trumpstellar ⛓️"
image="https://trumpstellar.github.io/img/USD.png"
conditions="KIND OF FUND RAISE USES"
status="live"
anchor_asset_type="FINANCIAL"
fixed_number=1000000000


[[CURRENCIES]]
code ="USD"
name ="US DOLLAR"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="FAST TOKEN OF YXRP FINANCE"
image="https://trumpstellar.github.io/img/USD.png"
conditions="There will only ever be 1 billion  tokens in existence.then lock issuer"
status="live"
anchor_asset_type="CHAIN"
fixed_number=1000000000

[[CURRENCIES]]
code ="SGB"
name ="SGB"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF TRUMPSTELLAR FINANCE"
image="https://trumpstellar.github.io/img/SGB.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000

[[CURRENCIES]]
code ="BTC"
name ="BITCOIN"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF TRUMPSTELLAR FINANCE"
image="https://trumpstellar.github.io/img/BTC.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000


[[CURRENCIES]]
code ="MANK"
name ="MANKI"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF TRUMPSTELLAR FINANCE"
image="https://trumpstellar.github.io/img/Manki.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000


[[CURRENCIES]]
code ="BELL"
name ="BELL"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/Bell.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000


[[CURRENCIES]]
code ="COIN"
name ="STELLAT COIN"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/COIN.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000



[[CURRENCIES]]
code ="OF"
name ="OF"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/Of.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000




[[CURRENCIES]]
code ="PINE"
name ="PINEPAL"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/Pinepal.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000



[[CURRENCIES]]
code ="CUP"
name ="CUP"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/Cup.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000





[[CURRENCIES]]
code ="RAUND"
name ="RAUND"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/Raund.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000




[[CURRENCIES]]
code ="FREE"
name ="FREE"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/free.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000




[[CURRENCIES]]
code ="DRAGON"
name ="DRAGON"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/Dregan.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000


[[CURRENCIES]]
code ="FROG"
name ="FROG"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/Frog.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000




[[CURRENCIES]]
code ="F"
name ="F"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/F.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000


[[CURRENCIES]]
code ="ETH"
name ="ETH"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/@.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000



[[CURRENCIES]]
code ="OK"
name ="OK"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/19.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000




[[CURRENCIES]]
code ="FLEM"
name ="FLEM"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/48.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000




[[CURRENCIES]]
code ="HART"
name ="HART"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/Hart.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000





[[CURRENCIES]]
code ="PUZZLE"
name ="PUZZLE"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/Puzal.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000


[[CURRENCIES]]
code ="STAR"
name ="STAR"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/STAR.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000


[[CURRENCIES]]
code ="DUCK"
name ="DUCK"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/3.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000

[[CURRENCIES]]
code ="REAR"
name ="REAR"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/18.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000

[[CURRENCIES]]
code ="TURTLE"
name ="TURTLE"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/T.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000

[[CURRENCIES]]
code ="WATCH"
name ="WATCH"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/Watch.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000


[[CURRENCIES]]
code ="DIMONF"
name ="DIMONF"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/21.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000

[[CURRENCIES]]
code ="100"
name ="100"
issuer = "GCBAYTUVFQQK7UJICZR3ETZ4JJHDBVME37OH6FQIFHX7FTODGSMCEGVU"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF trumpstellar FINANCE"
image="https://trumpstellar.github.io/img/100.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000
