# swees <sweespay.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
]

[DOCUMENTATION]
ORG_NAME="YXRP"
ORG_URL="https://yxrp.github.io/"
ORG_LOGO ="https://yxrp.github.io/img/crown.png"
ORG_OFFICIAL_EMAIL="YXRP@FINANCE"
ORG_SUPPORT_EMAIL="YXRP@FINANCE"
ORG_DESCRIPTION="YXRP FINANCE"

[[PRINCIPALS]]
email="YXRP@FINANCE"

[[CURRENCIES]]
code ="YXRP"
name ="YRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="Thes is make all type of payment yXRP ⛓️"
image="https://yxrp.github.io/img/YXRP.png"
conditions="KIND OF USES"
status="live"
anchor_asset_type="FINANCIAL"
fixed_number=1000000000


[[CURRENCIES]]
code ="AXRP"
name ="ARIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="FAST TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence.then lock issuer"
status="live"
anchor_asset_type="CHAIN"
fixed_number=1000000000

[[CURRENCIES]]
code ="BXRP"
name ="BRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000

[[CURRENCIES]]
code ="CXRP"
name ="CRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000


[[CURRENCIES]]
code ="DXRP"
name ="DRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000


[[CURRENCIES]]
code ="EXRP"
name ="ERIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000


[[CURRENCIES]]
code ="FXRP"
name ="FRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000



[[CURRENCIES]]
code ="GXRP"
name ="GRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000




[[CURRENCIES]]
code ="HXRP"
name ="HRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000



[[CURRENCIES]]
code ="IXRP"
name ="IRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000





[[CURRENCIES]]
code ="JXRP"
name ="JRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000




[[CURRENCIES]]
code ="KXRP"
name ="KRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000




[[CURRENCIES]]
code ="LXRP"
name ="LRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000


[[CURRENCIES]]
code ="MXRP"
name ="MRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000




[[CURRENCIES]]
code ="NXRP"
name ="NRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000


[[CURRENCIES]]
code ="OXRP"
name ="ORIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000



[[CURRENCIES]]
code ="PXRP"
name ="PRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000




[[CURRENCIES]]
code ="QXRP"
name ="QRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000




[[CURRENCIES]]
code ="RXRP"
name ="RRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000





[[CURRENCIES]]
code ="SXRP"
name ="SRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000


[[CURRENCIES]]
code ="TXRP"
name ="TRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000


[[CURRENCIES]]
code ="UXRP"
name ="URIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000

[[CURRENCIES]]
code ="VXRP"
name ="VRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000

[[CURRENCIES]]
code ="WXRP"
name ="WRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000

[[CURRENCIES]]
code ="XXRP"
name ="XRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000


[[CURRENCIES]]
code ="ZXRP"
name ="ZRIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000

[[CURRENCIES]]
code ="1XRP"
name ="1RIPPL"
issuer = "GC2VIJVUOZZ53MBSJFO5PTLWNDWMITTEOUACIOBDN2I3N4SLANINXRA2"
is_asset_anchored=false
display_decimals = 7
desc="SECOND TOKEN OF YXRP FINANCE"
image="https://yxrp.github.io/img/YXRP.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="CURRENCY"
fixed_number=1000000000
